// Code generated by libs/apierror/gen from proto/errors.json. DO NOT EDIT.

package apierror

// 全部注册错误码（spec-0.8）。
const (
	CodeValidationFailed Code = "AR_VALIDATION_FAILED"
	CodeCommonNotFound Code = "AR_COMMON_NOT_FOUND"
	CodeCommonConflict Code = "AR_COMMON_CONFLICT"
	CodeCommonNotImplemented Code = "AR_COMMON_NOT_IMPLEMENTED"
	CodeAuthUnauthenticated Code = "AR_AUTH_UNAUTHENTICATED"
	CodeAuthTokenExpired Code = "AR_AUTH_TOKEN_EXPIRED"
	CodeAuthForbidden Code = "AR_AUTH_FORBIDDEN"
	CodeTenantNotFound Code = "AR_TENANT_NOT_FOUND"
	CodeTenantSuspended Code = "AR_TENANT_SUSPENDED"
	CodeTenantContextMissing Code = "AR_TENANT_CONTEXT_MISSING"
	CodeInternalError Code = "AR_INTERNAL_ERROR"
	CodeUpstreamLlmTimeout Code = "AR_UPSTREAM_LLM_TIMEOUT"
	CodeUpstreamLlmFailed Code = "AR_UPSTREAM_LLM_FAILED"
	CodeUpstreamConnectorOffline Code = "AR_UPSTREAM_CONNECTOR_OFFLINE"
	CodeQuotaExceeded Code = "AR_QUOTA_EXCEEDED"
	CodeDatasourceNotFound Code = "AR_DATASOURCE_NOT_FOUND"
	CodeDatasourceNameConflict Code = "AR_DATASOURCE_NAME_CONFLICT"
	CodeDatasourceModeMismatch Code = "AR_DATASOURCE_MODE_MISMATCH"
	CodeDatasourceInUse Code = "AR_DATASOURCE_IN_USE"
	CodeAgentNotFound Code = "AR_AGENT_NOT_FOUND"
	CodeAliasConflict Code = "AR_ALIAS_CONFLICT"
	CodeIdempotencyReplay Code = "AR_IDEMPOTENCY_REPLAY"
	CodeConnectorEnrollTokenInvalid Code = "AR_CONNECTOR_ENROLL_TOKEN_INVALID"
	CodeConnectorAlreadyEnrolled Code = "AR_CONNECTOR_ALREADY_ENROLLED"
	CodeConnectorRevoked Code = "AR_CONNECTOR_REVOKED"
	CodeConnectorOffline Code = "AR_CONNECTOR_OFFLINE"
	CodeSvcUnauthenticated Code = "AR_SVC_UNAUTHENTICATED"
	CodeDatasourceConnectFailed Code = "AR_DATASOURCE_CONNECT_FAILED"
	CodeDatasourceTestTimeout Code = "AR_DATASOURCE_TEST_TIMEOUT"
	CodeMetricsCollectFailed Code = "AR_METRICS_COLLECT_FAILED"
	CodeSnapshotCollectFailed Code = "AR_SNAPSHOT_COLLECT_FAILED"
	CodeCollectUnsupportedKind Code = "AR_COLLECT_UNSUPPORTED_KIND"
	CodeTimeseriesWriteFailed Code = "AR_TIMESERIES_WRITE_FAILED"
	CodeTimeseriesQueryFailed Code = "AR_TIMESERIES_QUERY_FAILED"
	CodeTimeseriesUndeclaredSeries Code = "AR_TIMESERIES_UNDECLARED_SERIES"
	CodeCollectDatasourceMismatch Code = "AR_COLLECT_DATASOURCE_MISMATCH"
)

var codeMeta = map[Code]Meta{
	CodeValidationFailed: {Level: "E1", HTTP: 400, Message: "请求参数不合法", Deprecated: false},
	CodeCommonNotFound: {Level: "E3", HTTP: 404, Message: "请求的资源不存在", Deprecated: false},
	CodeCommonConflict: {Level: "E3", HTTP: 409, Message: "资源状态冲突，请刷新后重试", Deprecated: false},
	CodeCommonNotImplemented: {Level: "E4", HTTP: 501, Message: "该能力尚未实现", Deprecated: false},
	CodeAuthUnauthenticated: {Level: "E2", HTTP: 401, Message: "未登录或凭证无效", Deprecated: false},
	CodeAuthTokenExpired: {Level: "E2", HTTP: 401, Message: "登录已过期，请重新登录", Deprecated: false},
	CodeAuthForbidden: {Level: "E2", HTTP: 403, Message: "没有执行该操作的权限", Deprecated: false},
	CodeTenantNotFound: {Level: "E3", HTTP: 404, Message: "租户不存在", Deprecated: false},
	CodeTenantSuspended: {Level: "E2", HTTP: 403, Message: "租户已停用，请联系管理员", Deprecated: false},
	CodeTenantContextMissing: {Level: "E4", HTTP: 500, Message: "服务内部错误", Deprecated: false},
	CodeInternalError: {Level: "E4", HTTP: 500, Message: "服务内部错误", Deprecated: false},
	CodeUpstreamLlmTimeout: {Level: "E5", HTTP: 504, Message: "模型服务响应超时，请稍后重试", Deprecated: false},
	CodeUpstreamLlmFailed: {Level: "E5", HTTP: 502, Message: "模型服务暂不可用，请稍后重试", Deprecated: false},
	CodeUpstreamConnectorOffline: {Level: "E5", HTTP: 503, Message: "数据源接入器离线，请检查 Connector 状态", Deprecated: false},
	CodeQuotaExceeded: {Level: "E6", HTTP: 429, Message: "请求超出配额限制，请稍后重试", Deprecated: false},
	CodeDatasourceNotFound: {Level: "E3", HTTP: 404, Message: "数据源不存在", Deprecated: false},
	CodeDatasourceNameConflict: {Level: "E3", HTTP: 409, Message: "数据源名称已存在", Deprecated: false},
	CodeDatasourceModeMismatch: {Level: "E1", HTTP: 400, Message: "接入模式与连接配置不匹配", Deprecated: false},
	CodeDatasourceInUse: {Level: "E3", HTTP: 409, Message: "数据源正被引用，无法删除", Deprecated: false},
	CodeAgentNotFound: {Level: "E3", HTTP: 404, Message: "智能体不存在", Deprecated: false},
	CodeAliasConflict: {Level: "E3", HTTP: 409, Message: "别名已被占用", Deprecated: false},
	CodeIdempotencyReplay: {Level: "E1", HTTP: 409, Message: "幂等键已用于不同的请求", Deprecated: false},
	CodeConnectorEnrollTokenInvalid: {Level: "E2", HTTP: 401, Message: "注册令牌无效或已过期", Deprecated: false},
	CodeConnectorAlreadyEnrolled: {Level: "E3", HTTP: 409, Message: "该接入器已完成注册", Deprecated: false},
	CodeConnectorRevoked: {Level: "E2", HTTP: 403, Message: "该接入器已被吊销", Deprecated: false},
	CodeConnectorOffline: {Level: "E5", HTTP: 503, Message: "数据源接入器离线", Deprecated: false},
	CodeSvcUnauthenticated: {Level: "E2", HTTP: 401, Message: "服务间认证失败", Deprecated: false},
	CodeDatasourceConnectFailed: {Level: "E5", HTTP: 502, Message: "数据源连接失败", Deprecated: false},
	CodeDatasourceTestTimeout: {Level: "E5", HTTP: 504, Message: "数据源连接测试超时", Deprecated: false},
	CodeMetricsCollectFailed: {Level: "E5", HTTP: 502, Message: "指标采集失败", Deprecated: false},
	CodeSnapshotCollectFailed: {Level: "E5", HTTP: 502, Message: "快照采集失败", Deprecated: false},
	CodeCollectUnsupportedKind: {Level: "E4", HTTP: 400, Message: "不支持的采集类型", Deprecated: false},
	CodeTimeseriesWriteFailed: {Level: "E4", HTTP: 500, Message: "服务内部错误", Deprecated: false},
	CodeTimeseriesQueryFailed: {Level: "E4", HTTP: 500, Message: "服务内部错误", Deprecated: false},
	CodeTimeseriesUndeclaredSeries: {Level: "E4", HTTP: 500, Message: "服务内部错误", Deprecated: false},
	CodeCollectDatasourceMismatch: {Level: "E2", HTTP: 403, Message: "上报的数据源不属于该连接器", Deprecated: false},
}
