// Code generated by libs/apierror/gen from proto/errors.json. DO NOT EDIT.

package apierror

// 全部注册错误码（spec-0.8）。
const (
	CodeValidationFailed Code = "AR_VALIDATION_FAILED"
	CodeCommonNotFound Code = "AR_COMMON_NOT_FOUND"
	CodeCommonConflict Code = "AR_COMMON_CONFLICT"
	CodeCommonNotImplemented Code = "AR_COMMON_NOT_IMPLEMENTED"
	CodeAuthUnauthenticated Code = "AR_AUTH_UNAUTHENTICATED"
	CodeAuthTokenExpired Code = "AR_AUTH_TOKEN_EXPIRED"
	CodeAuthForbidden Code = "AR_AUTH_FORBIDDEN"
	CodeTenantNotFound Code = "AR_TENANT_NOT_FOUND"
	CodeTenantSuspended Code = "AR_TENANT_SUSPENDED"
	CodeTenantContextMissing Code = "AR_TENANT_CONTEXT_MISSING"
	CodeInternalError Code = "AR_INTERNAL_ERROR"
	CodeUpstreamLlmTimeout Code = "AR_UPSTREAM_LLM_TIMEOUT"
	CodeUpstreamLlmFailed Code = "AR_UPSTREAM_LLM_FAILED"
	CodeUpstreamConnectorOffline Code = "AR_UPSTREAM_CONNECTOR_OFFLINE"
	CodeQuotaExceeded Code = "AR_QUOTA_EXCEEDED"
)

var codeMeta = map[Code]Meta{
	CodeValidationFailed: {Level: "E1", HTTP: 400, Message: "请求参数不合法", Deprecated: false},
	CodeCommonNotFound: {Level: "E3", HTTP: 404, Message: "请求的资源不存在", Deprecated: false},
	CodeCommonConflict: {Level: "E3", HTTP: 409, Message: "资源状态冲突，请刷新后重试", Deprecated: false},
	CodeCommonNotImplemented: {Level: "E4", HTTP: 501, Message: "该能力尚未实现", Deprecated: false},
	CodeAuthUnauthenticated: {Level: "E2", HTTP: 401, Message: "未登录或凭证无效", Deprecated: false},
	CodeAuthTokenExpired: {Level: "E2", HTTP: 401, Message: "登录已过期，请重新登录", Deprecated: false},
	CodeAuthForbidden: {Level: "E2", HTTP: 403, Message: "没有执行该操作的权限", Deprecated: false},
	CodeTenantNotFound: {Level: "E3", HTTP: 404, Message: "租户不存在", Deprecated: false},
	CodeTenantSuspended: {Level: "E2", HTTP: 403, Message: "租户已停用，请联系管理员", Deprecated: false},
	CodeTenantContextMissing: {Level: "E4", HTTP: 500, Message: "服务内部错误", Deprecated: false},
	CodeInternalError: {Level: "E4", HTTP: 500, Message: "服务内部错误", Deprecated: false},
	CodeUpstreamLlmTimeout: {Level: "E5", HTTP: 504, Message: "模型服务响应超时，请稍后重试", Deprecated: false},
	CodeUpstreamLlmFailed: {Level: "E5", HTTP: 502, Message: "模型服务暂不可用，请稍后重试", Deprecated: false},
	CodeUpstreamConnectorOffline: {Level: "E5", HTTP: 503, Message: "数据源接入器离线，请检查 Connector 状态", Deprecated: false},
	CodeQuotaExceeded: {Level: "E6", HTTP: 429, Message: "请求超出配额限制，请稍后重试", Deprecated: false},
}
